package com.chatmod.mobile.ui

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Surface
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.chatmod.mobile.billing.PlayBillingUiState
import com.chatmod.mobile.ui.dashboard.BetaFeedbackCategory
import com.chatmod.mobile.ui.dashboard.CommandEditorState
import com.chatmod.mobile.ui.dashboard.DashboardScreen
import com.chatmod.mobile.ui.dashboard.DashboardTab
import com.chatmod.mobile.ui.dashboard.DashboardUiState
import com.chatmod.mobile.ui.dashboard.LogEntryFilter
import com.chatmod.mobile.ui.dashboard.TimerEditorState

@Composable
fun ChatModApp(
    state: DashboardUiState,
    playBilling: PlayBillingUiState,
    onToggleBot: () -> Unit,
    onSendSubscriberOnlyRecommendation: () -> Unit,
    onResolveQueueItem: (String) -> Unit,
    onDeleteQueueItem: (String) -> Unit,
    onQuickBlockQueueItem: (String) -> Unit,
    onWarnQueueItem: (String) -> Unit,
    onSuggestQueueItem: (String) -> Unit,
    onSelectTab: (DashboardTab) -> Unit,
    onRefreshUserWarnings: () -> Unit,
    onOpenUserProfile: (String) -> Unit,
    onUserProfileNotesChange: (String) -> Unit,
    onSaveUserProfileNotes: () -> Unit,
    onHideUserProfile: () -> Unit,
    onTimeoutUserProfile: () -> Unit,
    onUnbanUserProfile: (String, String?) -> Unit,
    onWhitelistUserProfile: () -> Unit,
    onTemporaryWhitelistUserProfile: () -> Unit,
    onDismissUserProfile: () -> Unit,
    onStreamChannelIdChange: (String) -> Unit,
    onUseConnectedYouTubeChannel: () -> Unit,
    onRefreshStreams: () -> Unit,
    onSelectStream: (String) -> Unit,
    onConnectionTestMessageChange: (String) -> Unit,
    onSendConnectionTestMessage: () -> Unit,
    onRunModeratorPermissionCheck: () -> Unit,
    onRefreshChannelProfiles: () -> Unit,
    onSelectChannelProfile: (String) -> Unit,
    onChannelProfileNameChange: (String) -> Unit,
    onChannelProfileChannelIdChange: (String) -> Unit,
    onCreateChannelProfile: () -> Unit,
    onRefreshRulePresets: () -> Unit,
    onSaveCurrentRulePreset: () -> Unit,
    onExportRulePresets: () -> Unit,
    onStartRulePresetImport: () -> Unit,
    onRulePresetImportTextChange: (String) -> Unit,
    onConfirmRulePresetImport: () -> Unit,
    onDismissRulePresetImport: () -> Unit,
    onToggleAutoReply: () -> Unit,
    onToggleFirstStreamMinutesOnly: () -> Unit,
    onToggleHideUserOnSevereMatch: () -> Unit,
    onSelectRulePreset: (String) -> Unit,
    onApplyRuleTemplate: (String) -> Unit,
    onCreateCommand: () -> Unit,
    onEditCommand: (String) -> Unit,
    onDeleteCommand: (String) -> Unit,
    onSendCommand: (String) -> Unit,
    onRefreshFaqEntries: () -> Unit,
    onStartCreateFaqEntry: () -> Unit,
    onStartEditFaqEntry: (String) -> Unit,
    onFaqQuestionChange: (String) -> Unit,
    onFaqAnswerChange: (String) -> Unit,
    onFaqKeywordsChange: (String) -> Unit,
    onFaqEnabledChange: (Boolean) -> Unit,
    onSaveFaqEntry: () -> Unit,
    onDeleteFaqEntry: (String) -> Unit,
    onCommandEditorChange: (CommandEditorState) -> Unit,
    onSaveCommand: () -> Unit,
    onDismissCommandEditor: () -> Unit,
    onCreateTimer: () -> Unit,
    onEditTimer: (String) -> Unit,
    onDeleteTimer: (String) -> Unit,
    onPauseAllTimers: () -> Unit,
    onResumeAllTimers: () -> Unit,
    onTimerEditorChange: (TimerEditorState) -> Unit,
    onSaveTimer: () -> Unit,
    onDismissTimerEditor: () -> Unit,
    onRefreshBillingProducts: () -> Unit,
    onPurchaseProduct: (String) -> Unit,
    onRestorePurchases: () -> Unit,
    onSimulateProPurchase: () -> Unit,
    onRefreshBackups: () -> Unit,
    onCreateSettingsBackup: () -> Unit,
    onExportAccount: () -> Unit,
    onConnectYouTube: () -> Unit,
    onDisconnectYouTube: () -> Unit,
    onDeleteAccount: () -> Unit,
    onWipeLocalData: () -> Unit,
    onDeleteBackup: (String) -> Unit,
    onRestoreBackup: (String) -> Unit,
    onConfirmAccountAction: () -> Unit,
    onDismissAccountAction: () -> Unit,
    onConfirmModerationAction: () -> Unit,
    onDismissModerationAction: () -> Unit,
    onRefreshSupportEvents: () -> Unit,
    onSendSupportDiagnostic: () -> Unit,
    onFeedbackCategoryChange: (BetaFeedbackCategory) -> Unit,
    onFeedbackMessageChange: (String) -> Unit,
    onSubmitBetaFeedback: () -> Unit,
    onSelectLogFilter: (LogEntryFilter) -> Unit,
    onRefreshProAnalytics: () -> Unit,
    onExportLogs: () -> Unit,
    onMarkFalsePositive: (String) -> Unit,
    onTuneFalsePositive: (String) -> Unit,
    onEmergencyModeChange: (Boolean) -> Unit,
    onLinkLockdownChange: (Boolean) -> Unit,
    onReducedMotionChange: (Boolean) -> Unit,
    onHighContrastChange: (Boolean) -> Unit,
    onLowDataModeChange: (Boolean) -> Unit,
    onShareUsageAnalyticsChange: (Boolean) -> Unit,
    onDiscordWebhookUrlChange: (String) -> Unit,
    onDiscordEnabledChange: (Boolean) -> Unit,
    onDiscordModerationAlertsChange: (Boolean) -> Unit,
    onDiscordRuntimeAlertsChange: (Boolean) -> Unit,
    onSaveDiscordWebhook: () -> Unit,
    onTestDiscordWebhook: () -> Unit,
    onDeleteDiscordWebhook: () -> Unit,
    onOverlayEnabledChange: (Boolean) -> Unit,
    onOverlayModerationActionsChange: (Boolean) -> Unit,
    onOverlayRuntimeStatusChange: (Boolean) -> Unit,
    onOverlayViewerStatsChange: (Boolean) -> Unit,
    onOverlayRecentChatChange: (Boolean) -> Unit,
    onSaveOverlayConfig: () -> Unit,
    onRotateOverlayToken: () -> Unit,
    onRefreshOverlayConfig: () -> Unit,
    onTeamInviteNameChange: (String) -> Unit,
    onTeamRedeemCodeChange: (String) -> Unit,
    onCreateTeamInvite: () -> Unit,
    onRedeemTeamInvite: () -> Unit,
    onRevokeTeamMember: (String) -> Unit,
    onRefreshTeamAccess: () -> Unit
) {
    Surface(modifier = Modifier.fillMaxSize()) {
        DashboardScreen(
            state = state,
            playBilling = playBilling,
            onToggleBot = onToggleBot,
            onSendSubscriberOnlyRecommendation = onSendSubscriberOnlyRecommendation,
            onResolveQueueItem = onResolveQueueItem,
            onDeleteQueueItem = onDeleteQueueItem,
            onQuickBlockQueueItem = onQuickBlockQueueItem,
            onWarnQueueItem = onWarnQueueItem,
            onSuggestQueueItem = onSuggestQueueItem,
            onSelectTab = onSelectTab,
            onRefreshUserWarnings = onRefreshUserWarnings,
            onOpenUserProfile = onOpenUserProfile,
            onUserProfileNotesChange = onUserProfileNotesChange,
            onSaveUserProfileNotes = onSaveUserProfileNotes,
            onHideUserProfile = onHideUserProfile,
            onTimeoutUserProfile = onTimeoutUserProfile,
            onUnbanUserProfile = onUnbanUserProfile,
            onWhitelistUserProfile = onWhitelistUserProfile,
            onTemporaryWhitelistUserProfile = onTemporaryWhitelistUserProfile,
            onDismissUserProfile = onDismissUserProfile,
            onStreamChannelIdChange = onStreamChannelIdChange,
            onUseConnectedYouTubeChannel = onUseConnectedYouTubeChannel,
            onRefreshStreams = onRefreshStreams,
            onSelectStream = onSelectStream,
            onConnectionTestMessageChange = onConnectionTestMessageChange,
            onSendConnectionTestMessage = onSendConnectionTestMessage,
            onRunModeratorPermissionCheck = onRunModeratorPermissionCheck,
            onRefreshChannelProfiles = onRefreshChannelProfiles,
            onSelectChannelProfile = onSelectChannelProfile,
            onChannelProfileNameChange = onChannelProfileNameChange,
            onChannelProfileChannelIdChange = onChannelProfileChannelIdChange,
            onCreateChannelProfile = onCreateChannelProfile,
            onRefreshRulePresets = onRefreshRulePresets,
            onSaveCurrentRulePreset = onSaveCurrentRulePreset,
            onExportRulePresets = onExportRulePresets,
            onStartRulePresetImport = onStartRulePresetImport,
            onRulePresetImportTextChange = onRulePresetImportTextChange,
            onConfirmRulePresetImport = onConfirmRulePresetImport,
            onDismissRulePresetImport = onDismissRulePresetImport,
            onToggleAutoReply = onToggleAutoReply,
            onToggleFirstStreamMinutesOnly = onToggleFirstStreamMinutesOnly,
            onToggleHideUserOnSevereMatch = onToggleHideUserOnSevereMatch,
            onSelectRulePreset = onSelectRulePreset,
            onApplyRuleTemplate = onApplyRuleTemplate,
            onCreateCommand = onCreateCommand,
            onEditCommand = onEditCommand,
            onDeleteCommand = onDeleteCommand,
            onSendCommand = onSendCommand,
            onRefreshFaqEntries = onRefreshFaqEntries,
            onStartCreateFaqEntry = onStartCreateFaqEntry,
            onStartEditFaqEntry = onStartEditFaqEntry,
            onFaqQuestionChange = onFaqQuestionChange,
            onFaqAnswerChange = onFaqAnswerChange,
            onFaqKeywordsChange = onFaqKeywordsChange,
            onFaqEnabledChange = onFaqEnabledChange,
            onSaveFaqEntry = onSaveFaqEntry,
            onDeleteFaqEntry = onDeleteFaqEntry,
            onCommandEditorChange = onCommandEditorChange,
            onSaveCommand = onSaveCommand,
            onDismissCommandEditor = onDismissCommandEditor,
            onCreateTimer = onCreateTimer,
            onEditTimer = onEditTimer,
            onDeleteTimer = onDeleteTimer,
            onPauseAllTimers = onPauseAllTimers,
            onResumeAllTimers = onResumeAllTimers,
            onTimerEditorChange = onTimerEditorChange,
            onSaveTimer = onSaveTimer,
            onDismissTimerEditor = onDismissTimerEditor,
            onRefreshBillingProducts = onRefreshBillingProducts,
            onPurchaseProduct = onPurchaseProduct,
            onRestorePurchases = onRestorePurchases,
            onSimulateProPurchase = onSimulateProPurchase,
            onRefreshBackups = onRefreshBackups,
            onCreateSettingsBackup = onCreateSettingsBackup,
            onExportAccount = onExportAccount,
            onConnectYouTube = onConnectYouTube,
            onDisconnectYouTube = onDisconnectYouTube,
            onDeleteAccount = onDeleteAccount,
            onWipeLocalData = onWipeLocalData,
            onDeleteBackup = onDeleteBackup,
            onRestoreBackup = onRestoreBackup,
            onConfirmAccountAction = onConfirmAccountAction,
            onDismissAccountAction = onDismissAccountAction,
            onConfirmModerationAction = onConfirmModerationAction,
            onDismissModerationAction = onDismissModerationAction,
            onRefreshSupportEvents = onRefreshSupportEvents,
            onSendSupportDiagnostic = onSendSupportDiagnostic,
            onFeedbackCategoryChange = onFeedbackCategoryChange,
            onFeedbackMessageChange = onFeedbackMessageChange,
            onSubmitBetaFeedback = onSubmitBetaFeedback,
            onSelectLogFilter = onSelectLogFilter,
            onRefreshProAnalytics = onRefreshProAnalytics,
            onExportLogs = onExportLogs,
            onMarkFalsePositive = onMarkFalsePositive,
            onTuneFalsePositive = onTuneFalsePositive,
            onEmergencyModeChange = onEmergencyModeChange,
            onLinkLockdownChange = onLinkLockdownChange,
            onReducedMotionChange = onReducedMotionChange,
            onHighContrastChange = onHighContrastChange,
            onLowDataModeChange = onLowDataModeChange,
            onShareUsageAnalyticsChange = onShareUsageAnalyticsChange,
            onDiscordWebhookUrlChange = onDiscordWebhookUrlChange,
            onDiscordEnabledChange = onDiscordEnabledChange,
            onDiscordModerationAlertsChange = onDiscordModerationAlertsChange,
            onDiscordRuntimeAlertsChange = onDiscordRuntimeAlertsChange,
            onSaveDiscordWebhook = onSaveDiscordWebhook,
            onTestDiscordWebhook = onTestDiscordWebhook,
            onDeleteDiscordWebhook = onDeleteDiscordWebhook,
            onOverlayEnabledChange = onOverlayEnabledChange,
            onOverlayModerationActionsChange = onOverlayModerationActionsChange,
            onOverlayRuntimeStatusChange = onOverlayRuntimeStatusChange,
            onOverlayViewerStatsChange = onOverlayViewerStatsChange,
            onOverlayRecentChatChange = onOverlayRecentChatChange,
            onSaveOverlayConfig = onSaveOverlayConfig,
            onRotateOverlayToken = onRotateOverlayToken,
            onRefreshOverlayConfig = onRefreshOverlayConfig,
            onTeamInviteNameChange = onTeamInviteNameChange,
            onTeamRedeemCodeChange = onTeamRedeemCodeChange,
            onCreateTeamInvite = onCreateTeamInvite,
            onRedeemTeamInvite = onRedeemTeamInvite,
            onRevokeTeamMember = onRevokeTeamMember,
            onRefreshTeamAccess = onRefreshTeamAccess
        )
    }
}
